var list = [
    'advise',
    'achievement',
    'admittance',
    'assistance',
    'abbreviation',
    'authority',
    'absorb',
    'advice',
    'analyze',
    'association',
    'capitol',
    'bacteria',
    'cinnamon',
    'campaign',
    'bicycle',
    'commotion',
    'benefiting',
    'boulevard',
];

var sentences = [
    'Please advise me of the next steps.',
    "That was a great achievement!",
    "Admittance to this university is dependent upon grades.",
    "I need some assistance with the computer.",
    "The use of abbreviation is common in texting.",
    "Who is the authority on this subject?",
    "Sponges absorb water very well.",
    "Can I have some advice?",
    "We need to analyze the situation to find the best solution.",
    "I am part of an international association.",
    "The government met at the capitol building to discuss their response.",
    "There are a lot of bacteria on that slide.",
    "Cinnamon rolls are delicious.",
    "The campaign is being launched on Monday.",
    "He rode his bicycle through town.",
    "The election of the new mayor caused quite a commotion.",
    "This anti-scam policy is benefiting the buyer more than the seller.",
    "We live near a boulevard."
]