var list = [
    'identical',
    'idle',
    'idol',
    'immediately',
    'immobilize',
    'impossibility',
    'inconvenient',
    'incredible',
    'infamous',
    'innocence',
    'instructor',
    'intelligent',
    'irate',
    'irresistible',
    'judgment',
    'juvenile',
    'kettle',
    'knitting',
];

var sentences = [
    "This apple looks identical to the other one.",
    "Don't just stand around idle for hours!",
    "You should not worship an idol.",
    "We will leave immediately once everyone is ready.",
    "Immobilize the vehicle before working on it.",
    "It's an impossibility that we'll find our way out.",
    "This is rather inconvenient.",
    "His work on this was an incredible feat.",
    "An infamous person is someone who has achieved high levels of fame.",
    "He maintained his innocence throughout the trial.",
    "My instructor was strict, but also fun to listen to.",
    "An intelligent person wouldn't have left that kind of mess.",
    "She was very irate after her car was rear-ended.",
    "The irresistible smell of popcorn drew me to the booth.",
    "Before you pass judgement, consider your own actions.",
    "Juvenile detention is a possibility.",
    "The kettle was hissing furiously on the stove.",
    "She was calmly knitting in her room upstairs."
]