var list = [
    'dismiss',
    'dessert',
    'destination',
    'detail',
    'discuss',
    'daylight',
    'defender',
    'deny',
    'desecration',
    'detach',
    'directory',
    'desire',
    'desert',
    'descent',
    'display',
    'division',
    'dormitory',
    'duet',
    'debris',
    'decade',
    'defeat',
    'delicate',
    'delivery',
    'deposit',
    'disapprove',
];

var sentences = [
    "I will dismiss everyone at the end of class.",
    "Dessert tonight is apple pie.",
    "You have arrived at your destination.",
    "Please review these documents in more detail.",
    "We can discuss any concerns you have tonight.",
    "It is better to work in daylight.",
    "Our defender has arrived!",
    "I will have to deny you access to that.",
    "They were confused about the unexplained desecration.",
    "Please detach the cable from the device.",
    "Look in the directory for his phone number.",
    "I have a strong desire for cake right now.",
    "Don't desert us!",
    "We began the perilous descent at noon.",
    "The art is on display.",
    "He was the best student in his division.",
    "All the boys shared one dormitory.",
    "They made a great duet.",
    "There was debris everywhere!",
    "This is the result of a decade of hard work.",
    "We suffered a great defeat.",
    "This is a very delicate matter.",
    "Please ensure you make the delivery.",
    "There is a 500 dollar deposit to join the program.",
    "I disapprove of paying that kind of money."
];