var list = [
    'clinch',
    'bachelor',
    'coarse',
    'cafeteria',
    'banjo',
    'civilian',
    'character',
    'cabinet',
    'crystallize',
    'crystal',
    'centigram',
    'button',
    'crept',
    'crutch',
    'calligraphy',
    'covet',
    'bonnet',
    'creditor',
    'copier',
    'buyer',
    'blouse',
    'contemporary',
    'contrary',
    'blonde',
    'conscience',
    'cement',
    'blanket',
    'belittle',
    'cologne',
    'carburetor',
    'bauble',
    'basin',
    'common',
    'colander',
    'camouflage',
    'baritone',
    'barbecue',
    'coffee'
];

var sentences = [
    'He was successfully able to clinch a good deal.',
    'The old bachelor demanded that we stay off his property.',
    'The grains of sand at the beach were quite coarse.',
    'Our school cafeteria serves the same meals every day.',
    'He plays the banjo for fun.',
    "This is a civilian matter.",
    "She's a great judge of character.",
    "We are not supposed to touch the medicine cabinet.",
    "Leave the powder in water for a few days and watch it crystallize.",
    "The crystal will be several inches long!",
    "A centigram is a very small amount.",
    "Press the button to make the door open.",
    "He slowly crept into the hallway, without making a sound.",
    "She uses a crutch to get around.",
    "That is some beautiful calligraphy!",
    "It's not right to covet other people's belongings.",
    "Well, she has a bee in her bonnet, doesn't she?",
    "The creditor will be repossessing their house tomorrow unless they can pay off their loan.",
    "Before everything went digital, copies had to be made manually using a copier.",
    "Have they found a buyer for the antique car?",
    "There is a blouse on sale at the clothing store.",
    "This painting is an example of contemporary art.",
    "On the contrary, I was not at the store at that time.",
    "He has blonde hair.",
    "Do you have a conscience?",
    "His bike smashed into the hard cement.",
    "Can someone get a blanket, please?",
    "Please stop trying to belittle the situation.",
    "Cologne has a very strong scent.",
    "The carburetor is malfunctioning.",
    "There are a number of baubles around the house.",
    "Someone brought a basin to the area.",
    "Everyone had a common interest in mind.",
    "Mom strained the beans using a colander.",
    "Chameleons have excellent natural camouflage.",
    "He had a deep baritone voice.",
    "Dad cooked the burgers on the barbecue.",
    "I can't do anything without my morning coffee."
]
