var list = [
    'adequate',
    'aluminum',
    'abolish',
    'accident',
    'algebra',
    'audible',
    'awful',
    'alchemy',
    'autumn',
    'athlete',
    'ailment',
    'attorney',
    'associate',
    'adverb',
    'ascend',
    'arise',
    'adventure',
    'approval',
    'advisor',
    'appreciate',
    'advantage',
    'admissible',
    'ancient',
    'adopt',
    'absence'
];

var sentences = [
    'Make sure to use an adequate amount of soap.',
    'I picked up four aluminum cans.',
    'We need to abolish littering in our state.',
    'He spilled the milk on the floor by accident.',
    'My least favorite subject is algebra.',
    'The smoke alarm made a very audible sound.',
    'The fumes from the paint can were awful.',
    'My alchemy experiments have been unsuccessful in creating gold.',
    'Autumn is my favorite season of the year.',
    'He was an accomplished athlete.',
    "I've heard that garlic can relieve many ailments.",
    "She hired an attorney to help her in the court case.",
    "My parents don't want me to associate with John.",
    "I need to include more adverbs in my writing.",
    "I struggled to ascend the stairs after my run this morning.",
    "It's time to arise from uncertainty.",
    "Climbing Mount Everest would be a thrilling adventure.",
    "This spelling list has won my approval.",
    "My advisor recommended that I practice my spelling further.",
    "She greatly appreciated his willingness to help.",
    "He had the advantage of having more time to study for the test.",
    "His work on the essay was deemed admissible.",
    "Would you like to visit the ancient Parthenon?",
    "She adopted the practice of picking up litter on her way to school.",
    "The teacher demanded an explanation for his frequent absence."
]