var list = [
    'badge',
    'basic',
    'basket',
    'basketball',
    'battle',
    'beast',
    'beetle',
    'beggar',
    'blame',
    'blank',
    'board',
    'boast',
    'borrow',
    'bottle',
    'brain',
    'branch',
    'brave',
    'breath',
    'bridge',
    'bubble',
    'bucket',
    'burst'
];

var sentences = [
    'We got a badge for being well behaved on our field trip.',
    "Make sure to bring basic necessities, like clothes and food.",
    "We passed around a basket at church to collect donations.",
    "I played basketball in the park with my friends.",
    "In History class, we learned about a particularly fascinating battle.",
    "The beast was 3 times the size of a human.",
    "A beetle is a type of insect.",
    "The beggar on the side of the road asked for some money.",
    "Don't put the blame on others for something you did yourself.",
    "I drew a blank while trying to remember the answer.",
    "I guess it's time to go back to the drawing board.",
    "He loves to boast about his marks in class.",
    "Can I borrow your pencil?",
    "My water bottle is almost empty.",
    "My brain is about to explode!",
    "I pruned a branch off the tree on my way to school.",
    "We must be brave in order to face this challenging time.",
    "I'm going outside for a breath of fresh air.",
    "Don't cross that bridge. It's very weak!",
    "I can blow a bubble through this hole.",
    "Please bring a bucket of water.",
    "She burst through the door."
]