var list = [
    'from',
    'going',
    'few',
    'fresh',
    'flat',
    'glad',
    'fell',
    'flag',
    'gull',
    'free',
    'give',
    'father',
    'grit',
    'fort',
    'girl',
    'fast',
    'grew',
    'foot',
    'gift',
    'farther',
    'green',
    'fool',
    'gray',
    'first',
    'gave',
    'farm',
    'fog',
    'gone',
    'fine',
    'gang',
    'far',
    'fly',
    'game',
    'fang',
    'golf',
    'fill',
    'fry',
    'flew',
];

var sentences = [
    'Where are you from?',
    "I am going to the park with Jim.",
    "There are only a few people signed up.",
    "There are fresh berries on the table.",
    "The terrain is nice and flat here.",
    "I am glad you had fun!",
    "While we were at the park, I fell off one of the climbing structures.",
    "Can you raise the flag?",
    "Look at that large gull!",
    "I can't wait to be free of school.",
    "Can you give me some more time to finish?",
    "My father is taking me on a trip this weekend.",
    "There is a lot of grit in your shoes.",
    "We're going to be building a fort up north.",
    "Did you see how fast that girl ran today?",
    "Did you see how fast that girl ran today?",
    "This tree definitely grew since we planted it a few years ago.",
    "After I sprained my ankle, I was hobbling on one foot.",
    "I really want to get a gift for my friend this Christmas.",
    "We have gone a lot farther than we should have.",
    "Look at how green that forest is!",
    "I'm such a fool; I didn't bring the compass.",
    "Uh oh. The sky is already turning gray.",
    "We're going to be the first people to ever get lost here.",
    "I gave him a good excuse to leave.",
    "We need to get back to the farm before it gets dark!",
    "The fog is piling up fast.",
    "Soon even the trees will be gone!",
    "We'll be fine; we just have to keep moving.",
    "The gang will come looking for us if we don't come back. I hope.",
    "We're not too far away.",
    "I wish we had wings and could fly back.",
    "That's not how the game of life works.",
    "Isn't that a jaguar over there? Look at the fangs on that thing!",
    "I really wish I was just playing on the golf course like usual.",
    "Well, we certainly got our fill of adventures.",
    "Can you fry those eggs, please?",
    "That bee just flew right past us!"
];