var list = [
    'been',
    'bird',
    'bark',
    'born',
    'again',
    'as',
    'bill',
    'book',
    'after',
    'by',
    'bang',
    'bike',
    'bone',
    'add',
    'bug',
    'bake',
    'best',
    'blue',
    'brown',
    'baby',
    'bent',
    'block',
    'brother',
    'ask',
    'belt',
    'blew',
    'brook',
    'arm',
    'being',
    'black',
    'apart',
    'bring',
    'birth',
    'bee',
    'beat',
    'brag',
    'any',
];

var sentences = [
    'How have you been doing?',
    'The bird is really high up in the sky.',
    'The rough bark on this tree is painful to touch.',
    "I don't remember the day I was born, obviously.",
    "Have you forgotten to take the bread out again?",
    "It was as if he had never existed.",
    "Your bill is 100 dollars.",
    "Can I see that book you are reading?",
    "I'll be ready after my meeting.",
    "By the time I get there, it will be too late.",
    "The starter went off with a bang!",
    "I am riding my bike later today.",
    "I have a bone to pick with you.",
    "Add the following numbers to your sheet.",
    "That bug looks disgusting.",
    "I love to bake!",
    "I wish you all the best.",
    "My favorite color is blue.",
    "My least favorite color is brown.",
    "She is taking time off work once the baby is born.",
    "My bicycle wheel is quite bent.",
    "Put a block of wood in front of it so it doesn't go anywhere.",
    "Ask your brother for help!",
    "Ask your brother for help!",
    "Your belt is too loose.",
    "I blew into my hands to try and warm up.",
    "It was quite peaceful near the brook.",
    "My arm felt like it would fall off.",
    "My little sister is being annoying.",
    "That horse over there is black!",
    "Keep those two chemicals apart, otherwise bad things will happen.",
    "Can you bring me that glass?",
    "The birth of Jesus is a very special time.",
    "Be careful; that bee might sting you!",
    "Do you like the beat of that music?",
    "He always wants to brag about his grades.",
    "Any suggestions are appreciated."
];
