
var title = "LA Lesson 101";

var list = [
    'than',
    'about',
    'back',
    'after',
    'I\'m',
    'been',
    'big',
    'came',
    'away',
    'your',
    'who',
    'when',
    'them',
    'because',
    'from',
    'have',
    'there',
    'any',
    'into',
    'just',
    'little',
    'make',
    'before',
    'two',
    'four',
    'mother',
    'where',
    'very',
    'could',
    'were',
    'over',
    'ride',
    'don\'t',
    'said',
    'that',
    'one',
    'with',
    'five',
    'their',
    'what',
    'but',
    'here',
    'going',
    'our',
    'three',
    'want',
    'able',
    'bad',
    'give',
    'today',
]

var sentences = [
    'I would rather eat peaches than plums.',
    'Tell us what you know about bears!',
    'I will be back in 3 hours.',
    'I will be available after my meeting finishes.',
    "I'm quite disappointed in you.",
    "I have been working quite hard recently.",
    "That dog is really big!",
    "I came back from work a few minutes ago.",
    "How long will you be away for?",
    "Your phone is ringing.",
    "Who is that tall man on the sidewalk?",
    "You can go outside when it stops raining.",
    "Don't talk to them!",
    "I was late because the subway was delayed.",
    "He is from Colorado.",
    "I have no idea where I dropped my phone.",
    "There is no way I could have dropped it here.",
    "I would appreciate any suggestions of where to look.",
    "I ran into the house to hide from the storm.",
    "Just seconds later, thunder roared overhead.",
    "Little did I know the worst was yet to come.",
    "Make sure you turn off the stove before leaving!",
    "Before I moved here, I used to live in Montreal.",
    "Those two people look really happy together.",
    "I have four more cookies.",
    "My mother will be mad if I don't head home now.",
    "Where did you come from?",
    "I am very excited for Christmas!",
    "I could help you with your homework tonight.",
    "Were you also at the fair?",
    "Don't go over that bridge; it's ready to tumble!",
    "I am going to ride the train tomorrow.",
    "I don't think you should go that way.",
    "He said my suit looked really nice.",
    "That tree grows really tasty peaches.",
    "One day, I will become a pilot.",
    "I am heading to the park with Jim.",
    "We have five people signed up already!",
    "Their dog is noticeably healthier now.",
    "What is that noise?",
    "I want to go, but I have too much homework.",
    "I'm here. Where are you?",
    "Are you going to answer my question?",
    "Our family is going to Florida this winter.",
    "There are three attractions we're planning to see.",
    "Do you want to go with us?",
    "I wish I was able to.",
    "Ah, that's too bad.",
    "I would give my front teeth to be able to go!",
    "Well, not today, but maybe some other time."
];